#!/usr/bin/env python3
"""Generates te-data.mjs: base encodings, glyph-name -> Unicode map and standard 14 Latin font widths.
Sources (independent of PDFium and PDF.js):
  - reportlab 4.4.10 reportlab.pdfbase._fontdata: encodings (PDF 1.7 Annex D glyph names) and Adobe Core14 AFM widths
  - pypdf 5.9.0 pypdf._codecs.adobe_glyphs: Adobe Glyph List (name -> Unicode)
Symbol and ZapfDingbats are deliberately excluded: True Edit gates those fonts.
"""
import json, sys
import reportlab, pypdf
from reportlab.pdfbase import _fontdata as fd
from pypdf._codecs import adobe_glyphs as AG

out = sys.argv[1]
encs = {}
for key, name in (('StandardEncoding', 'StandardEncoding'), ('WinAnsiEncoding', 'WinAnsiEncoding'), ('MacRomanEncoding', 'MacRomanEncoding')):
    e = fd.encodings[name]
    arr = [n if n else None for n in e]
    assert len(arr) == 256, name
    encs[key] = arr
# PDF 1.7 Annex D: WinAnsiEncoding also maps 0240 to 'space' and 0255 to 'hyphen'; reportlab uses the
# Windows names (nbspace/sfthyphen, if present). Keep reportlab's names; the reverse map prefers the lowest code.
fonts = ['Helvetica', 'Helvetica-Bold', 'Helvetica-Oblique', 'Helvetica-BoldOblique',
         'Times-Roman', 'Times-Bold', 'Times-Italic', 'Times-BoldItalic',
         'Courier', 'Courier-Bold', 'Courier-Oblique', 'Courier-BoldOblique']
widths = {f: {g: int(w) for g, w in fd.widthsByFontGlyph[f].items()} for f in fonts}
names = set()
for arr in encs.values():
    names.update(n for n in arr if n)
for f in fonts:
    names.update(widths[f].keys())
g2u = {}
missing = []
for n in sorted(names):
    v = AG.get('/' + n)
    if v is None:
        missing.append(n)
        continue
    cps = [ord(ch) for ch in v]
    g2u[n] = cps[0] if len(cps) == 1 else cps
lines = [
    '// Generated by tests/tools/gen_te_data.py. Do not edit by hand.',
    f'// Sources: reportlab {reportlab.Version} (PDF Annex D encodings, Adobe Core14 AFM widths),',
    f'// pypdf {pypdf.__version__} (Adobe Glyph List). ASCII only.',
    'export const TE_DATA_VERSION = ' + json.dumps('te-data-1 reportlab ' + reportlab.Version + ' pypdf ' + pypdf.__version__) + ';',
    'export const BASE_ENCODINGS = ' + json.dumps(encs, separators=(',', ':')) + ';',
    'export const GLYPH_TO_UNICODE = ' + json.dumps(g2u, separators=(',', ':'), sort_keys=True) + ';',
    'export const STD14_WIDTHS = ' + json.dumps(widths, separators=(',', ':'), sort_keys=True) + ';',
    'export const STD14_ALIASES = ' + json.dumps({'Arial': 'Helvetica', 'Arial,Bold': 'Helvetica-Bold', 'Arial,Italic': 'Helvetica-Oblique', 'Arial,BoldItalic': 'Helvetica-BoldOblique', 'TimesNewRoman': 'Times-Roman', 'TimesNewRoman,Bold': 'Times-Bold', 'TimesNewRoman,Italic': 'Times-Italic', 'TimesNewRoman,BoldItalic': 'Times-BoldItalic', 'CourierNew': 'Courier', 'CourierNew,Bold': 'Courier-Bold', 'CourierNew,Italic': 'Courier-Oblique', 'CourierNew,BoldItalic': 'Courier-BoldOblique'}) + ';',
    '',
]
text = '\n'.join(lines)
assert all(ord(c) < 128 for c in text)
open(out, 'w').write(text)
print('glyph names', len(names), 'mapped', len(g2u), 'unmapped', missing[:20], 'bytes', len(text))
print('WinAnsi 0x80', encs['WinAnsiEncoding'][0x80], 'A0', encs['WinAnsiEncoding'][0xA0], 'AD', encs['WinAnsiEncoding'][0xAD], '20', encs['WinAnsiEncoding'][0x20])
print('Helvetica Euro', widths['Helvetica'].get('Euro'), 'space', widths['Helvetica']['space'])
